package com.GUI.form.NhanVien;

import DAO.NhanVienDAO;
import Entity.NhanVien;
import Utilities.Option;
import Utilities.ValidateCheck;
import Utilities.XImage;

/**
 *
 * @author Admin
 */
public class ChangePassForm extends javax.swing.JFrame {

    private ValidateCheck vld = new ValidateCheck();
    private XImage xImage = new XImage();
    private NhanVienDAO nvdao = new NhanVienDAO();
    private Option dialog = new Option();
    private String pass = "";

    /**
     * Creates new form ChangePassForm
     */
    public ChangePassForm() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.GUI.swing.PanelBorder();
        lblavatar = new com.GUI.swing.ImageAvatar();
        txttennhanvien = new javax.swing.JLabel();
        txtoldpass = new com.GUI.swing.PasswordField();
        txtnewpass1 = new com.GUI.swing.PasswordField();
        txtnewpass2 = new com.GUI.swing.PasswordField();
        btnchangepass = new com.GUI.swing.Button();
        btncancel = new com.GUI.swing.Button();
        txtmanhanvien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBorder1.setBackground(new java.awt.Color(56, 56, 56));

        lblavatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/GUI/icon/0cf1c017d3491b174258.jpg"))); // NOI18N

        txttennhanvien.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        txttennhanvien.setForeground(new java.awt.Color(255, 255, 255));
        txttennhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txttennhanvien.setText("Tên Nhân Viên");

        txtoldpass.setText("passwordField1");
        txtoldpass.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        txtoldpass.setLabelText("Old PassWord");

        txtnewpass1.setText("passwordField1");
        txtnewpass1.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        txtnewpass1.setLabelText("New PassWord");

        txtnewpass2.setText("passwordField1");
        txtnewpass2.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        txtnewpass2.setLabelText("Confirm PassWord");

        btnchangepass.setBackground(new java.awt.Color(255, 0, 0));
        btnchangepass.setBorder(null);
        btnchangepass.setForeground(new java.awt.Color(255, 255, 255));
        btnchangepass.setText("Đổi Mật Khẩu");
        btnchangepass.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        btnchangepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangepassActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(255, 0, 0));
        btncancel.setBorder(null);
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Hủy");
        btncancel.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        txtmanhanvien.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        txtmanhanvien.setForeground(new java.awt.Color(255, 255, 255));
        txtmanhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtmanhanvien.setText("Mã Nhân Viên");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtoldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtnewpass1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnewpass2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(btnchangepass, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lblavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtmanhanvien)
                .addGap(18, 18, 18)
                .addComponent(txttennhanvien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtoldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnewpass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnewpass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnchangepass, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnchangepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangepassActionPerformed
        // TODO add your handling code here:
        ChangePass();
    }//GEN-LAST:event_btnchangepassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.GUI.swing.Button btncancel;
    private com.GUI.swing.Button btnchangepass;
    private com.GUI.swing.ImageAvatar lblavatar;
    private com.GUI.swing.PanelBorder panelBorder1;
    private javax.swing.JLabel txtmanhanvien;
    private com.GUI.swing.PasswordField txtnewpass1;
    private com.GUI.swing.PasswordField txtnewpass2;
    private com.GUI.swing.PasswordField txtoldpass;
    private javax.swing.JLabel txttennhanvien;
    // End of variables declaration//GEN-END:variables
    public void initEntity(String imglink, String manv, String tennv) {
        xImage.ReadAndScaleIMG(lblavatar, "/imageNhanVien/" + imglink, lblavatar.getWidth() - 1, lblavatar.getHeight() - 1);
        txtmanhanvien.setText(manv);
        txttennhanvien.setText(tennv);
    }

    private void getpass() {

    }

    private boolean validatepass() {
        String oldpass = txtoldpass.getText();
        String newpass1 = txtnewpass1.getText();
        String newpass2 = txtnewpass2.getText();
        if (vld.CheckString("Mật Khẩu Cũ", oldpass, 30, false)
                && vld.CheckString("Mật Khẩu Mới", oldpass, 30, false)
                && vld.CheckString("Nhập Lại Mật Khẩu Mới", oldpass, 30, false)
                && vld.CheckDulicase2("Mật Khẩu Cũ", oldpass, "Mật Khẩu Của Bạn\nVui Lòng Nhập Lại!", pass)
                && vld.CheckDulicase2("Mật Khẩu Mới", newpass1, "Nhập Lại Mật Khẩu Mới", newpass2)) {
            return true;
        }
        return false;
    }

    private void ChangePass() {
        if (validatepass()) {
            try {
                NhanVien pass = new NhanVien();
                pass.setMaNhanVien(txtmanhanvien.getText());
                pass.setMatKhau("123");
                nvdao.UpdatePassword(pass);
                dialog.Done(this, "Đổi Mật Khẩu Thành Công", "Hoàn Thành");
            } catch (Exception e) {
                dialog.Error(this, "Đổi Mật Khẩu Không Thành Công\n" + e, "Lỗi");
            }
        }
    }

}
